### ISSUE TITLE
Sometimes getting panic after long duration

### ISSUE THREAD

**Issue by jilleJr** [jilleJr/kubectl-klock#12]
After letting `kubectl klock pods` sit there for 20-30 min, it eventually panics.

Error:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d96c36]

goroutine 89 [running]:
github.com/jilleJr/kubectl-klock/pkg/klock.decodeIntoTable({0x0, 0x0})
	/home/kallefagerberg/code/jillejr/kubectl-klock/pkg/klock/decoder.go:44 +0x36
github.com/jilleJr/kubectl-klock/pkg/klock.(*Printer).PrintObj(0xc000095ec8?, {0x0?, 0x0?}, {0x0, 0x0})
	/home/kallefagerberg/code/jillejr/kubectl-klock/pkg/klock/klock.go:177 +0x38
github.com/jilleJr/kubectl-klock/pkg/klock.Execute.func1()
	/home/kallefagerberg/code/jillejr/kubectl-klock/pkg/klock/klock.go:151 +0x492
github.com/jilleJr/kubectl-klock/pkg/klock.Execute.func2()
	/home/kallefagerberg/code/jillejr/kubectl-klock/pkg/klock/klock.go:161 +0x38
created by github.com/jilleJr/kubectl-klock/pkg/klock.Execute
	/home/kallefagerberg/code/jillejr/kubectl-klock/pkg/klock/klock.go:160 +0x5f8
```

Probably Kubernetes sending a ping or something when nothing has happened in a while.

**Comment by jilleJr** [comment]
I did not check if the watch channel was closed.

Changed that in 107a0bf

Let's see if it errors with that.

**Comment by jilleJr** [comment]
Issue has been solved.
